import { runCopilotQuery } from '../copilot/engine'
import type { CopilotConversation, CopilotContext } from '../types/copilot'
import type { OpeningId } from '../types/domain'
import { candidates } from './candidates'

/**
 * Deterministic prototype chat history for the standalone Copilot workspace.
 * Each seed conversation is generated by actually calling the engine against
 * the base (un-overridden) candidate data, so what you see on click is
 * exactly what Copilot would say if you asked it fresh — not hand-written
 * copy that could drift from the real intent-matching logic.
 */
function buildContext(openingId: OpeningId | null): CopilotContext {
  return {
    level: openingId ? 'role' : 'global',
    openingId,
    candidateId: null,
    filters: [],
    candidates,
  }
}

function buildConversation(
  id: string,
  title: string,
  query: string,
  openingId: OpeningId | null,
  createdAt: number,
): CopilotConversation {
  const context = buildContext(openingId)
  return {
    id,
    title,
    createdAt,
    stickyOpeningId: openingId,
    lastCandidateIds: [],
    turns: [{ id: `${id}-1`, query, result: runCopilotQuery(query, context) }],
  }
}

const HOUR = 60 * 60 * 1000
const DAY = 24 * HOUR
const now = Date.now()

export const seedConversations: CopilotConversation[] = [
  buildConversation('seed-spd-shortlist', 'Senior Product Designer shortlist', 'Who should I review?', 'senior-product-designer', now - 2 * HOUR),
  buildConversation(
    'seed-pm-top',
    'Product Manager top candidates',
    'check product manager top candidates',
    null,
    now - 3 * HOUR,
  ),
  buildConversation('seed-feedback-blockers', 'Interview feedback blockers', "What's blocking this role?", 'senior-product-designer', now - 5 * HOUR),
  buildConversation(
    'seed-compare-ananya-rahul',
    'Compare Ananya and Rahul',
    'Compare Ananya and Rahul',
    'senior-product-designer',
    now - DAY - 2 * HOUR,
  ),
  buildConversation(
    'seed-uxr-pipeline',
    'UX Researcher pipeline review',
    'Who should I review for UX Researcher?',
    null,
    now - DAY - 4 * HOUR,
  ),
]

export const seedConversationOrder = seedConversations.map((conversation) => conversation.id)
export const seedConversationsById: Record<string, CopilotConversation> = Object.fromEntries(
  seedConversations.map((conversation) => [conversation.id, conversation]),
)
